apiVersion: v1
entries:
  redis:
  - appVersion: 4.0.10
    created: 2018-07-08T11:14:23.3555889+02:00
    description: Open source, advanced key-value store. It is often referred to as
      a data structure server since keys can contain strings, hashes, lists, sets
      and sorted sets.
    digest: bc641e28012634e31d7556f5808184081d2ae30c85f064d1165f22ac47996b38
    engine: gotpl
    home: http://redis.io/
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - email: containers@bitnami.com
      name: bitnami-bot
    name: redis
    sources:
    - https://github.com/bitnami/bitnami-docker-redis
    urls:
    - redis-3.6.0.tgz
    version: 3.6.0
  - appVersion: 4.0.10
    created: 2018-07-08T11:14:23.3545889+02:00
    description: Open source, advanced key-value store. It is often referred to as
      a data structure server since keys can contain strings, hashes, lists, sets
      and sorted sets.
    digest: 0df64040ad41da41b5f99908518113b3f70de4f9640d0c0d5b2a21bceb97133b
    engine: gotpl
    home: http://redis.io/
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - email: containers@bitnami.com
      name: bitnami-bot
    name: redis
    sources:
    - https://github.com/bitnami/bitnami-docker-redis
    urls:
    - redis-3.5.0.tgz
    version: 3.5.0
  - appVersion: 4.0.10
    created: 2018-07-08T11:14:23.3535888+02:00
    description: Open source, advanced key-value store. It is often referred to as
      a data structure server since keys can contain strings, hashes, lists, sets
      and sorted sets.
    digest: 3009b1c98eaee9001ce6962cd833f38dc8e9d382dfd64706e4efe664609da7bf
    engine: gotpl
    home: http://redis.io/
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - email: containers@bitnami.com
      name: bitnami-bot
    name: redis
    sources:
    - https://github.com/bitnami/bitnami-docker-redis
    urls:
    - redis-3.4.3.tgz
    version: 3.4.3
generated: 2018-07-08T11:14:23.3525931+02:00
