apiVersion: v1
entries:
  redis:
  - appVersion: 3.2.9
    created: 2018-07-01T18:10:24.3284139+02:00
    description: Open source, advanced key-value store. It is often referred to as
      a data structure server since keys can contain strings, hashes, lists, sets
      and sorted sets.
    digest: fca91c1c5617fad6a1849bcb381e55908a925240328047a46c72db390e22cb58
    engine: gotpl
    home: http://redis.io/
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - email: containers@bitnami.com
      name: bitnami-bot
    name: redis
    sources:
    - https://github.com/bitnami/bitnami-docker-redis
    urls:
    - redis-0.10.2.tgz
    version: 0.10.2
generated: 2018-07-01T18:10:24.3263783+02:00
